<?php

use Nitrapi\Nitrapi;

function ark_server_status_page_top(&$page_top): void {
  $key = \Drupal::service('key.repository');
  $accessToken = $key->getKey('nitrado_token')->getKeyValue();
  $api = new \Nitrapi\Nitrapi($accessToken);
  print '<pre>';
  print_r($api->getServices()[0]->api->info['gameserver']['status']);
  print '</pre>';
//  $api->getService('Gameserver')->
//  $service = \Drupal::service('ark_server_status.helper');
//  $serverList = $service->getServerList();
//  $serverBoolen = $service->checkServer('servername', $serverList);
}



